# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=release
endif
export config

PROJECTS := eyez-test eyez-opencv

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

eyez-test: 
	@echo "==== Building eyez-test ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f eyez-test.make

eyez-opencv: 
	@echo "==== Building eyez-opencv ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f eyez-opencv.make

clean:
	@${MAKE} --no-print-directory -C . -f eyez-test.make clean
	@${MAKE} --no-print-directory -C . -f eyez-opencv.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   eyez-test"
	@echo "   eyez-opencv"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
