# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=release
endif
export config

PROJECTS := eyez

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

eyez: 
	@echo "==== Building eyez ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f eyez.make

clean:
	@${MAKE} --no-print-directory -C . -f eyez.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   eyez"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
